package com.zackehh.javaspaces.util;

import com.zackehh.javaspaces.auction.IWsBid;
import com.zackehh.javaspaces.auction.IWsLot;
import com.zackehh.javaspaces.constants.Constants;
import net.jini.space.JavaSpace;

import javax.swing.text.JTextComponent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;

public class InterfaceUtils {

    /**
     * Default constructor which should not be called. All method calls
     * should be called from a static context.
     */
    private InterfaceUtils(){
        throw new UnsupportedOperationException();
    }

    /**
     * Parse a text input as a Number. Should the input not be
     * a valid Number, set errorTextOut to display a parse error.
     *
     * @param  component    the component to retrieve text of
     * @return Number       a valid Number object
     */
    public static Number getTextAsNumber(JTextComponent component){
        try {
            return NumberFormat.getInstance().parse(component.getText());
        } catch(ParseException e){
            return null;
        }
    }

    /**
     * Parse a Double to a currency formatted string.
     *
     * @param  value        the Double value to convert
     * @return Double       a valid currency string
     */
    public static String getDoubleAsCurrency(Double value){
        DecimalFormat currencyEnforcer = new DecimalFormat("0.00");
        if(value == null){
            return null;
        }
        return "£" + currencyEnforcer.format(value);
    }

    /**
     * Returns a List of bids associated with the passed in lot.
     * Converts the string history from inside the lot to gather
     * the bid IDs associated with the lot. It is here that
     * the logic for private bids takes place, with a user ID
     * replacement to "Anonymous Buyer" if the bid is private and
     * not created by the current user.
     *
     * @param  lot          the IWsLot to gather history for
     * @return ArrayList    the list of bids associated
     */
    public static ArrayList<IWsBid> getBidHistory(IWsLot lot){
        JavaSpace space = SpaceUtils.getSpace();

        ArrayList<IWsBid> bidHistory = new ArrayList<IWsBid>();

        try {
            IWsLot lotTemplate = new IWsLot(lot.getId(), null, null, null, null, null);
            IWsLot refreshedLot = (IWsLot) space.read(lotTemplate, null, Constants.SPACE_TIMEOUT);

            String[] bids = refreshedLot.getHistory().split(",");

            if(bids.length <= 1){
                return bidHistory;
            }

            for(int i = 1; i < bids.length; i++){
                IWsBid template = new IWsBid(Integer.parseInt(bids[i]), null, lot.getId(), null, null);
                IWsBid bidItem = ((IWsBid) space.read(template, null, Constants.SPACE_TIMEOUT));

                if(!bidItem.isAnonymous()) {
                    bidItem.setUserId("Anonymous Buyer");
                }

                bidHistory.add(bidItem);
            }
        } catch(Exception e){
            e.printStackTrace();
        }
        Collections.sort(bidHistory, new Comparator<IWsBid>() {
            @Override
            public int compare(IWsBid bid1, IWsBid bid2) {
                return bid2.getPrice().compareTo(bid1.getPrice());
            }
        });
        return bidHistory;
    }

    /**
     * Returns a bid history generated by InterfaceUtils#getBidHistory
     * in the format of Vector<Vector<String>> so it can be passed in
     * to a table model and displayed more easily.
     *
     * @param  lot          the IWsLot to gather history for
     * @return Vector       a matrix of IWsBid values
     */
    public static Vector<Vector<String>> getVectorBidMatrix(IWsLot lot){
        ArrayList<IWsBid> bids = getBidHistory(lot);

        Vector<Vector<String>> values = new Vector<Vector<String>>();

        for(int iY = 0; iY < bids.size(); iY++){
            final IWsBid bid = bids.get(iY);
            values.add(iY, new Vector<String>(){{
                add(bid.getUserId());
                add(InterfaceUtils.getDoubleAsCurrency(bid.getPrice()));
            }});
        }

        return values;
    }

    /**
     * Returns a String converted to CamelCase when using
     * argument split as a delimiter for the split.
     *
     * @param  str          the string to convert
     * @param  split        the split delimiter
     * @return String       the camelCase string
     */
    public static String toCamelCase(String str, String split){
        String[] parts = str.toLowerCase().split(split);
        String camelCaseString = "";
        int i = 0;
        for (String part : parts){
            if(i++ > 0) {
                camelCaseString +=
                        part.substring(0, 1).toUpperCase() +
                                part.substring(1).toLowerCase();
            } else {
                camelCaseString += part;
            }
        }
        return camelCaseString;
    }

}
